-- Continuum Prompt 40 (Prompt 39A Section 5): board error code catalogue.
-- GENERATED by clinical/db/errorcataloguegen.mjs from error_catalogue.data.mjs.
-- Apply AFTER 007_migration_error_catalogue.sql. One transaction, idempotent.
-- Maps a board code to an element ONLY, never a value, polarity or correction. No dashes.

begin;

insert into clinical.wcb_error_catalogue(jurisdiction_code,board_code,element_name,confidence,legacy_note,source) values
  ('AB','121023','Alberta PHN',0.85,'Legacy 2007 return file wording (7.02) has inverted polarity versus the current "Patient does not have an Alberta PHN" element (Y means no PHN). Mapped to the element only; never seed a value or a correction.','7.02 - Sample Batch Return File (with error).txt')
on conflict (jurisdiction_code, board_code) do nothing;

commit;
