-- Continuum Prompt 39: functional measurement seed (internal restriction codes + axis map).
-- GENERATED by clinical/db/functionalmeasurementgen.mjs from functional_measurement.data.mjs.
-- Apply AFTER 011_migration_functional_measurement_model.sql. One transaction, idempotent.
-- The axis map is the Section 4.4 board matrix (39A refined) that resolve_axes reads. No dashes.

begin;

insert into clinical.internal_restriction_code (code, label, free_text_phrase) values
  ('R05','No repetitive lifting','No repetitive lifting'),
  ('R10','No use of force or physical intervention','No use of force or physical intervention'),
  ('R11','No restraint or take downs','No restraint or take downs'),
  ('R13','No night shift or shift work','No night shift or rotating shift work'),
  ('R18','Concussion restrictions','Concussion protocol restrictions apply, see comments'),
  ('R19','Psychological restrictions','Psychological injury restrictions apply, see comments'),
  ('R20','Post surgical restrictions','Post surgical restrictions apply, see comments'),
  ('R22','Weight bearing restriction','Weight bearing restriction, see comments')
on conflict (code) do update
  set label = excluded.label, free_text_phrase = excluded.free_text_phrase, active = true;

insert into clinical.functional_axis_map (form_id, axis, ui_mapping, code_list_name, code_set, quantity_kind, display_order, source_version) values
  ('C050E','sitting','hours','Extended Work Restriction Codes','extended','hours',1,'prompt-39-2026-08-10'),
  ('C050E','standing','hours','Extended Work Restriction Codes','extended','hours',2,'prompt-39-2026-08-10'),
  ('C050E','walking','hours','Extended Work Restriction Codes','extended','hours',3,'prompt-39-2026-08-10'),
  ('C050E','driving','hours','Extended Work Restriction Codes','extended','hours',4,'prompt-39-2026-08-10'),
  ('C050E','bending','able_limited_unable','Basic Work Restriction Codes','basic','none',5,'prompt-39-2026-08-10'),
  ('C050E','twisting','able_limited_unable','Basic Work Restriction Codes','basic','none',6,'prompt-39-2026-08-10'),
  ('C050E','kneeling_squatting','able_limited_unable','Basic Work Restriction Codes','basic','none',7,'prompt-39-2026-08-10'),
  ('C050E','climbing','able_limited_unable','Basic Work Restriction Codes','basic','none',8,'prompt-39-2026-08-10'),
  ('C050E','pushing_pulling','able_limited_unable','Basic Work Restriction Codes','basic','none',9,'prompt-39-2026-08-10'),
  ('C050E','lifting_general','weight_kg','Weight Category Codes','weight','weight',10,'prompt-39-2026-08-10'),
  ('C050E','overhead_reaching','able_limited_unable','Basic Work Restriction Codes','basic','none',11,'prompt-39-2026-08-10'),
  ('C151','sitting','hours','Extended Work Restriction Codes','extended','hours',1,'prompt-39-2026-08-10'),
  ('C151','standing','hours','Extended Work Restriction Codes','extended','hours',2,'prompt-39-2026-08-10'),
  ('C151','walking','hours','Extended Work Restriction Codes','extended','hours',3,'prompt-39-2026-08-10'),
  ('C151','driving','hours','Extended Work Restriction Codes','extended','hours',4,'prompt-39-2026-08-10'),
  ('C151','bending','able_limited_unable','Basic Work Restriction Codes','basic','none',5,'prompt-39-2026-08-10'),
  ('C151','twisting','able_limited_unable','Basic Work Restriction Codes','basic','none',6,'prompt-39-2026-08-10'),
  ('C151','kneeling_squatting','able_limited_unable','Basic Work Restriction Codes','basic','none',7,'prompt-39-2026-08-10'),
  ('C151','climbing','able_limited_unable','Basic Work Restriction Codes','basic','none',8,'prompt-39-2026-08-10'),
  ('C151','pushing_pulling','able_limited_unable','Basic Work Restriction Codes','basic','none',9,'prompt-39-2026-08-10'),
  ('C151','lifting_general','weight_kg','Weight Category Codes','weight','weight',10,'prompt-39-2026-08-10'),
  ('C151','overhead_reaching','able_limited_unable','Basic Work Restriction Codes','basic','none',11,'prompt-39-2026-08-10'),
  ('C050S','sitting','hours','Extended Work Restriction Codes','extended','hours',1,'prompt-39-2026-08-10'),
  ('C050S','standing','hours','Extended Work Restriction Codes','extended','hours',2,'prompt-39-2026-08-10'),
  ('C050S','walking','hours','Extended Work Restriction Codes','extended','hours',3,'prompt-39-2026-08-10'),
  ('C050S','driving','hours','Extended Work Restriction Codes','extended','hours',4,'prompt-39-2026-08-10'),
  ('C050S','bending','hours','Extended Work Restriction Codes','extended','hours',5,'prompt-39-2026-08-10'),
  ('C050S','twisting','hours','Extended Work Restriction Codes','extended','hours',6,'prompt-39-2026-08-10'),
  ('C050S','kneeling_squatting','hours','Extended Work Restriction Codes','extended','hours',7,'prompt-39-2026-08-10'),
  ('C050S','climbing','hours','Extended Work Restriction Codes','extended','hours',8,'prompt-39-2026-08-10'),
  ('C050S','pushing_pulling','weight_kg','Extended Work Restriction Codes','extended','weight',9,'prompt-39-2026-08-10'),
  ('C050S','lifting_floor_to_waist','weight_kg','Weight Category Codes','weight','weight',10,'prompt-39-2026-08-10'),
  ('C050S','lifting_waist_to_shoulder','weight_kg','Weight Category Codes','weight','weight',11,'prompt-39-2026-08-10'),
  ('C050S','lifting_above_shoulder','weight_kg','Weight Category Codes','weight','weight',12,'prompt-39-2026-08-10'),
  ('C050S','reaching_left_above','able_unable',null,'able_unable_only','none',13,'prompt-39-2026-08-10'),
  ('C050S','reaching_left_below','able_unable',null,'able_unable_only','none',14,'prompt-39-2026-08-10'),
  ('C050S','reaching_right_above','able_unable',null,'able_unable_only','none',15,'prompt-39-2026-08-10'),
  ('C050S','reaching_right_below','able_unable',null,'able_unable_only','none',16,'prompt-39-2026-08-10'),
  ('C050S','grasping_left','able_unable',null,'able_unable_only','none',17,'prompt-39-2026-08-10'),
  ('C050S','grasping_right','able_unable',null,'able_unable_only','none',18,'prompt-39-2026-08-10'),
  ('C050S','environment','environment_flags',null,'environment','none',19,'prompt-39-2026-08-10'),
  ('C151S','sitting','hours','Extended Work Restriction Codes','extended','hours',1,'prompt-39-2026-08-10'),
  ('C151S','standing','hours','Extended Work Restriction Codes','extended','hours',2,'prompt-39-2026-08-10'),
  ('C151S','walking','hours','Extended Work Restriction Codes','extended','hours',3,'prompt-39-2026-08-10'),
  ('C151S','driving','hours','Extended Work Restriction Codes','extended','hours',4,'prompt-39-2026-08-10'),
  ('C151S','bending','hours',null,'conditional','hours',5,'prompt-39-2026-08-10'),
  ('C151S','twisting','hours',null,'conditional','hours',6,'prompt-39-2026-08-10'),
  ('C151S','kneeling_squatting','hours',null,'conditional','hours',7,'prompt-39-2026-08-10'),
  ('C151S','climbing','hours',null,'conditional','hours',8,'prompt-39-2026-08-10'),
  ('C151S','pushing_pulling','weight_kg',null,'conditional','weight',9,'prompt-39-2026-08-10'),
  ('C151S','lifting_floor_to_waist','weight_kg','Weight Category Codes','weight','weight',10,'prompt-39-2026-08-10'),
  ('C151S','lifting_waist_to_shoulder','weight_kg','Weight Category Codes','weight','weight',11,'prompt-39-2026-08-10'),
  ('C151S','lifting_above_shoulder','weight_kg','Weight Category Codes','weight','weight',12,'prompt-39-2026-08-10'),
  ('C151S','reaching_left_above','able_unable',null,'able_unable_only','none',13,'prompt-39-2026-08-10'),
  ('C151S','reaching_left_below','able_unable',null,'able_unable_only','none',14,'prompt-39-2026-08-10'),
  ('C151S','reaching_right_above','able_unable',null,'able_unable_only','none',15,'prompt-39-2026-08-10'),
  ('C151S','reaching_right_below','able_unable',null,'able_unable_only','none',16,'prompt-39-2026-08-10'),
  ('C151S','grasping_left','able_unable',null,'able_unable_only','none',17,'prompt-39-2026-08-10'),
  ('C151S','grasping_right','able_unable',null,'able_unable_only','none',18,'prompt-39-2026-08-10'),
  ('C151S','environment','environment_flags',null,'environment','none',19,'prompt-39-2026-08-10')
on conflict (form_id, axis) do update
  set ui_mapping = excluded.ui_mapping, code_list_name = excluded.code_list_name,
      code_set = excluded.code_set, quantity_kind = excluded.quantity_kind,
      display_order = excluded.display_order, source_version = excluded.source_version;

commit;
