/* Continuum Prompt 40: capability code set seed generator. Reads the reviewed
   source capability_code_set.data.mjs and emits 006_seed_capability_code_set.sql.
   Apply after 005_migration_capability_code_set.sql. Validates the source shape
   and mirrors it into SQL; no interpretation. No dashes anywhere.

   Run: node clinical/db/capabilitycodesetgen.mjs */

import { writeFileSync } from "node:fs";
import { ROWS } from "./capability_code_set.data.mjs";

const OUT = new URL("./006_seed_capability_code_set.sql", import.meta.url);
const SRC = "2025.04";
const SETS = new Set(["basic", "extended", "conditional", "able_unable_only"]);
const q = (v) => v === null || v === undefined ? "null" : "'" + String(v).replace(/'/g, "''") + "'";

// -- validate (fail loudly, write nothing on a bad row) ---------------------
const errors = [];
const seen = new Set();
ROWS.forEach((r, i) => {
  const at = "row[" + i + "] " + (r.form_id || "?") + " " + (r.obx_identifier || "?");
  if (!r.form_id) errors.push(at + ": missing form_id");
  if (!r.obx_identifier) errors.push(at + ": missing obx_identifier");
  if (!r.element_label) errors.push(at + ": missing element_label");
  if (!SETS.has(r.code_set)) errors.push(at + ": bad code_set " + JSON.stringify(r.code_set));
  if (r.code_set === "conditional") {
    if (!r.conditional_flag_obx || !r.conditional_basic_value) errors.push(at + ": conditional needs flag and basic value");
  } else if (r.conditional_flag_obx || r.conditional_basic_value) {
    errors.push(at + ": non conditional row must not carry a flag");
  }
  const key = r.form_id + "|" + r.obx_identifier;
  if (seen.has(key)) errors.push(at + ": duplicate (form, obx) " + key);
  seen.add(key);
});
if (errors.length) { console.error("SOURCE INVALID, nothing written:\n  " + errors.join("\n  ")); process.exit(1); }

// -- emit -------------------------------------------------------------------
const COLS = "form_id,obx_identifier,element_label,code_set,conditional_flag_obx,conditional_basic_value,source_version";
const out = [];
out.push("-- Continuum Prompt 40 (Prompt 39A Section 2.3): per (form, capability element) code set.");
out.push("-- GENERATED by clinical/db/capabilitycodesetgen.mjs from capability_code_set.data.mjs.");
out.push("-- Apply AFTER 005_migration_capability_code_set.sql. One transaction, idempotent. No dashes.");
out.push("");
out.push("begin;");
out.push("");
out.push("insert into clinical.wcb_capability_code_set(" + COLS + ") values");
out.push(ROWS.map((r) => "  (" + [
  q(r.form_id), q(r.obx_identifier), q(r.element_label), q(r.code_set),
  q(r.conditional_flag_obx || null), q(r.conditional_basic_value || null), q(SRC)
].join(",") + ")").join(",\n") + "\non conflict (form_id, obx_identifier) do nothing;");
out.push("");
out.push("commit;");
out.push("");
writeFileSync(OUT, out.join("\n"), "utf8");

// -- report -----------------------------------------------------------------
console.log("== capability code set seed generation ==");
console.log("output: " + OUT.pathname.replace(/^\//, ""));
console.log("total rows: " + ROWS.length);
const byForm = {};
for (const r of ROWS) { byForm[r.form_id] = byForm[r.form_id] || {}; byForm[r.form_id][r.code_set] = (byForm[r.form_id][r.code_set] || 0) + 1; }
for (const f of Object.keys(byForm)) console.log("  " + f + ": " + JSON.stringify(byForm[f]));
