/* Continuum Prompt 40: error catalogue seed generator. Reads the reviewed source
   error_catalogue.data.mjs and emits 008_seed_error_catalogue.sql. Apply after
   007_migration_error_catalogue.sql. Validates the source shape and mirrors it;
   no interpretation, and it refuses any row that carries a value or correction
   field (those must never exist). No dashes anywhere.

   Run: node clinical/db/errorcataloguegen.mjs */

import { writeFileSync } from "node:fs";
import { ROWS } from "./error_catalogue.data.mjs";

const OUT = new URL("./008_seed_error_catalogue.sql", import.meta.url);
const q = (v) => v === null || v === undefined ? "null" : "'" + String(v).replace(/'/g, "''") + "'";

// -- validate (fail loudly, write nothing on a bad row) ---------------------
const FORBIDDEN = ["value", "required_value", "polarity", "correction", "fix"];
const errors = [];
const seen = new Set();
ROWS.forEach((r, i) => {
  const at = "row[" + i + "] " + (r.board_code || "?");
  if (!r.jurisdiction_code) errors.push(at + ": missing jurisdiction_code");
  if (!r.board_code) errors.push(at + ": missing board_code");
  if (!r.source) errors.push(at + ": missing source");
  if (typeof r.confidence !== "number" || r.confidence < 0 || r.confidence > 1) errors.push(at + ": confidence must be a number 0 to 1");
  // structural guard: a catalogue row must never carry a value, polarity or correction (39A Section 5).
  for (const f of FORBIDDEN) if (f in r) errors.push(at + ": forbidden field " + JSON.stringify(f) + "; the catalogue maps a code to an element only");
  const key = r.jurisdiction_code + "|" + r.board_code;
  if (seen.has(key)) errors.push(at + ": duplicate (jurisdiction, board_code) " + key);
  seen.add(key);
});
if (errors.length) { console.error("SOURCE INVALID, nothing written:\n  " + errors.join("\n  ")); process.exit(1); }

// -- emit -------------------------------------------------------------------
const COLS = "jurisdiction_code,board_code,element_name,confidence,legacy_note,source";
const out = [];
out.push("-- Continuum Prompt 40 (Prompt 39A Section 5): board error code catalogue.");
out.push("-- GENERATED by clinical/db/errorcataloguegen.mjs from error_catalogue.data.mjs.");
out.push("-- Apply AFTER 007_migration_error_catalogue.sql. One transaction, idempotent.");
out.push("-- Maps a board code to an element ONLY, never a value, polarity or correction. No dashes.");
out.push("");
out.push("begin;");
out.push("");
out.push("insert into clinical.wcb_error_catalogue(" + COLS + ") values");
out.push(ROWS.map((r) => "  (" + [
  q(r.jurisdiction_code), q(r.board_code), q(r.element_name || null),
  Number(r.confidence).toFixed(2), q(r.legacy_note || null), q(r.source)
].join(",") + ")").join(",\n") + "\non conflict (jurisdiction_code, board_code) do nothing;");
out.push("");
out.push("commit;");
out.push("");
writeFileSync(OUT, out.join("\n"), "utf8");

// -- report -----------------------------------------------------------------
console.log("== error catalogue seed generation ==");
console.log("output: " + OUT.pathname.replace(/^\//, ""));
console.log("rows: " + ROWS.length + " (the catalogue grows from real rejections; the package has one)");
ROWS.forEach((r) => console.log("  " + r.board_code + " -> " + (r.element_name || "(unmapped)") + " conf " + r.confidence));
