/* Continuum Prompt 40: form_rule seed generator. Reads the human reviewed
   structured source (form_rules.data.mjs) and emits
   clinical/db/004_seed_form_rules.sql. Apply AFTER 003 (needs form_element for
   the rules to point at, and form_definition for the id).

   The source is authored from the transcription docs, not from memory, and every
   row's verified_against_sample_xml stays false until the rule is confirmed
   against its board 5.xx sample XML (the transcription docs' definition of done).
   This generator does no interpretation; it validates the source shape and mirrors
   it into SQL. No dashes anywhere.

   Run: node clinical/db/formrulegen.mjs */

import { writeFileSync } from "node:fs";
import { RULES } from "./form_rules.data.mjs";

const OUT = new URL("./004_seed_form_rules.sql", import.meta.url);
const JUR = "AB", VERSION = "1.0", SRC = "2025.04";
const RULE_TYPES = new Set(["show_hide", "business", "code_list_switch", "help_text"]);

const q = (v) => v === null || v === undefined ? "null" : "'" + String(v).replace(/'/g, "''") + "'";
const jb = (obj) => "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb";
const arr = (list) => list && list.length ? "array[" + list.map(q).join(",") + "]::varchar(200)[]" : "array[]::varchar(200)[]";

// -- validate the source (fail loudly, never emit a bad rule) ---------------
const errors = [];
const seen = new Set();
RULES.forEach((x, i) => {
  const at = "rule[" + i + "] " + (x.form_id || "?") + " " + (x.rule_code || "?");
  if (!x.form_id) errors.push(at + ": missing form_id");
  if (!x.rule_code) errors.push(at + ": missing rule_code");
  if (!RULE_TYPES.has(x.rule_type)) errors.push(at + ": bad rule_type " + JSON.stringify(x.rule_type));
  if (!x.source_document) errors.push(at + ": missing source_document");
  if (!Number.isInteger(x.source_page)) errors.push(at + ": source_page must be an int");
  if (!x.trigger_condition || typeof x.trigger_condition !== "object") errors.push(at + ": trigger_condition must be an object");
  if (!Array.isArray(x.affected_element_names) || x.affected_element_names.length === 0) errors.push(at + ": affected_element_names must be a non empty array");
  if (x.rule_type === "code_list_switch" && !x.switches_code_list_to) errors.push(at + ": code_list_switch needs switches_code_list_to");
  (x.affected_element_names || []).forEach((a) => { if (a && a.length > 200) errors.push(at + ": an affected name exceeds 200 chars"); });
  if (x.trigger_element_name && x.trigger_element_name.length > 200) errors.push(at + ": trigger_element_name exceeds 200 chars");
  // uniqueness on (form_id, source_document, source_page, rule_code, ordinal), the table's key
  const key = [x.form_id, x.source_document, x.source_page, x.rule_code, x.ordinal].join("|");
  if (seen.has(key)) errors.push(at + ": duplicate key " + key);
  seen.add(key);
});
if (errors.length) { console.error("SOURCE INVALID, nothing written:\n  " + errors.join("\n  ")); process.exit(1); }

// -- group by form, emit ----------------------------------------------------
const byForm = new Map();
for (const x of RULES) { if (!byForm.has(x.form_id)) byForm.set(x.form_id, []); byForm.get(x.form_id).push(x); }

const COLS = "rule_code,ordinal,rule_type,source_document,source_page,trigger_element_name,trigger_condition,affected_element_names,clears_on_hide,switches_code_list_to,verified_against_sample_xml,unresolvable";
const out = [];
out.push("-- Continuum Prompt 40: form_rule seed. GENERATED by clinical/db/formrulegen.mjs");
out.push("-- from the human reviewed source clinical/db/form_rules.data.mjs. Apply AFTER 003.");
out.push("-- One transaction, idempotent (on conflict do nothing). verified_against_sample_xml is");
out.push("-- true only where the verification pass confirmed the rule (so far: C050E BR5 / VAL-X01,");
out.push("-- the PHN inversion). Everything else pending. No dashes anywhere.");
out.push("");
out.push("begin;");
out.push("");
for (const [form, rules] of byForm) {
  out.push("-- " + form + " (" + rules.length + " rules)");
  out.push("insert into clinical.form_rule(form_definition_id," + COLS + ")");
  out.push("select fd.id, r.rule_code, r.ordinal::int, r.rule_type, r.source_document, r.source_page::int,");
  out.push("       r.trigger_element_name, r.trigger_condition::jsonb, r.affected_element_names,");
  out.push("       r.clears_on_hide::boolean, r.switches_code_list_to, r.verified_against_sample_xml::boolean, r.unresolvable::boolean");
  out.push("from clinical.form_definition fd");
  out.push("join (values");
  out.push(rules.map((x) => "  (" + [
    q(x.rule_code), x.ordinal, q(x.rule_type), q(x.source_document), x.source_page,
    q(x.trigger_element_name), jb(x.trigger_condition), arr(x.affected_element_names),
    (x.clears_on_hide ? "true" : "false"), q(x.switches_code_list_to),
    (x.verified_against_sample_xml ? "true" : "false"), (x.unresolvable ? "true" : "false")
  ].join(",") + ")").join(",\n"));
  out.push(") as r(" + COLS + ") on true");
  out.push("where fd.jurisdiction_code=" + q(JUR) + " and fd.form_id=" + q(form) + " and fd.version=" + q(VERSION));
  out.push("on conflict (form_definition_id,source_document,source_page,rule_code,ordinal) do nothing;");
  out.push("");
}
out.push("commit;");
out.push("");
writeFileSync(OUT, out.join("\n"), "utf8");

// -- report ------------------------------------------------------------------
console.log("== form_rule seed generation ==");
console.log("output: " + OUT.pathname.replace(/^\//, ""));
console.log("total rules: " + RULES.length);
for (const [form, rules] of byForm) {
  const byType = {};
  rules.forEach((x) => { byType[x.rule_type] = (byType[x.rule_type] || 0) + 1; });
  const ver = rules.filter((x) => x.verified_against_sample_xml).length;
  const unres = rules.filter((x) => x.unresolvable).length;
  const cls = rules.filter((x) => x.switches_code_list_to).length;
  console.log("  " + form + ": " + rules.length + " rules  " + JSON.stringify(byType) + "  verified=" + ver + " unresolvable=" + unres + " code_list_switch=" + cls);
}
console.log("\nNOTE: verified_against_sample_xml true only for confirmed rules; the rest await sample XML verification and Hannah sign off before go live.");
