/* Continuum Prompt 40: OBX skeleton seed generator. Reads each form's board
   sample XML and extracts the ORDERED list of OBX.3/CE.1 identifiers, which is the
   fixed skeleton the board emits for that form (Prompt 39A Section 3.1). Emits
   010_seed_obx_skeleton.sql. Apply after 009_migration_obx_skeleton.sql.

   The skeleton is read from the board's own reference files, not authored: for
   the clinical forms the Min sample carries the identical OBX set as the Max
   sample (39A: 5.03 C050E Min has the same 98 OBX as the Max, 73 of them empty),
   so the Min sample defines the full skeleton. The invoice forms carry a small
   fixed set. Acceptance criterion 4 is that a generated C050E matches the 98 OBX
   of 5.03 in order.

   Run: node clinical/db/obxskeletongen.mjs "<dir with the 5.xx sample XML files>"
   No dashes anywhere. */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const dir = process.argv[2];
if (!dir) { console.error('usage: node obxskeletongen.mjs "<dir with 5.xx sample XML>"'); process.exit(2); }
const OUT = new URL("./010_seed_obx_skeleton.sql", import.meta.url);
const OUT_DATA = new URL("./obx_skeleton.data.mjs", import.meta.url);
const SRC = "2025.04";
const q = (v) => v === null || v === undefined ? "null" : "'" + String(v).replace(/'/g, "''") + "'";

// The sample that defines each form's full OBX skeleton. Min fields where the
// board provides it (Min == Max for the OBX set on the clinical forms), the sole
// report sample for the invoice forms.
const FORM_SAMPLE = {
  C050E: /^5\.03 .*C050E .*Min Fields\.xml$/i,
  C050S: /^5\.06 .*C050S .*Min Fields\.xml$/i,
  C151: /^5\.08 .*C151 .*Min Fields\.xml$/i,
  C151S: /^5\.10 .*C151S .*Min Fields\.xml$/i,
  C568: /^5\.11 .*C568\.xml$/i,
  C568A: /^5\.13 .*C568A .*Attached Text\.xml$/i,
  C569: /^5\.15 .*C569\.xml$/i,
  C570: /^5\.16 .*C570\.xml$/i
};
// Both the underscore extracted names and the original spaced names must match.
const norm = (s) => s.replace(/_/g, " ");

// Extract OBX.3/CE.1 identifiers in document order.
function obxIdentifiers(xml) {
  const out = [];
  const re = /<OBX>([\s\S]*?)<\/OBX>/g;
  let m;
  while ((m = re.exec(xml))) {
    const block = m[1];
    const id = block.match(/<OBX\.3>[\s\S]*?<CE\.1>([\s\S]*?)<\/CE\.1>[\s\S]*?<\/OBX\.3>/i);
    out.push(id ? id[1].trim() : "");
  }
  return out;
}

const files = readdirSync(dir);
function findSample(re) { return files.find((f) => re.test(norm(f))); }

// -- extract per form, validate --------------------------------------------
const EXPECTED = { C050E: 98 }; // criterion 4: 5.03 C050E has 98 OBX
const skeletons = {};
const errors = [];
for (const [form, re] of Object.entries(FORM_SAMPLE)) {
  const file = findSample(re);
  if (!file) { errors.push(form + ": no sample XML matching " + re + " in " + dir); continue; }
  const ids = obxIdentifiers(readFileSync(dir + "/" + file, "utf8"));
  if (ids.some((x) => x === "")) errors.push(form + ": an OBX has no identifier in " + file);
  if (new Set(ids).size !== ids.length) errors.push(form + ": duplicate OBX identifiers in " + file);
  if (EXPECTED[form] != null && ids.length !== EXPECTED[form]) errors.push(form + ": expected " + EXPECTED[form] + " OBX, got " + ids.length + " (criterion 4)");
  skeletons[form] = { file, ids };
}
if (errors.length) { console.error("EXTRACTION FAILED, nothing written:\n  " + errors.join("\n  ")); process.exit(1); }

// -- emit -------------------------------------------------------------------
const out = [];
out.push("-- Continuum Prompt 40 (Prompt 39A Section 3.1): per form OBX skeleton, in fixed order.");
out.push("-- GENERATED by clinical/db/obxskeletongen.mjs from the board sample XML files.");
out.push("-- Apply AFTER 009_migration_obx_skeleton.sql. One transaction, idempotent. No dashes.");
out.push("");
out.push("begin;");
out.push("");
for (const [form, sk] of Object.entries(skeletons)) {
  out.push("-- " + form + " (" + sk.ids.length + " observations, from " + sk.file.replace(/_/g, " ") + ")");
  out.push("insert into clinical.wcb_obx_skeleton(form_id,ordinal,obx_identifier,source_sample) values");
  out.push(sk.ids.map((id, i) => "  (" + [q(form), i + 1, q(id), q(sk.file.replace(/_/g, " "))].join(",") + ")").join(",\n") + "\non conflict (form_id, ordinal) do nothing;");
  out.push("");
}
out.push("commit;");
out.push("");
writeFileSync(OUT, out.join("\n"), "utf8");

// -- also emit a data module the engine verifier reads (same rows) ----------
const data = [];
data.push("/* Continuum Prompt 40: per form OBX skeleton, in fixed order. GENERATED by");
data.push("   clinical/db/obxskeletongen.mjs from the board sample XML. Do not hand edit;");
data.push("   regenerate from the samples. The engine verifier clinical/engine/obx.mjs reads");
data.push("   these ROWS to assert a generated OBX set matches the skeleton. No dashes. */");
data.push("");
data.push("export const ROWS = [");
for (const [form, sk] of Object.entries(skeletons))
  sk.ids.forEach((id, i) => data.push("  { form_id: " + q(form) + ", ordinal: " + (i + 1) + ", obx_identifier: " + q(id) + " },"));
data.push("];");
data.push("");
writeFileSync(OUT_DATA, data.join("\n"), "utf8");

// -- report -----------------------------------------------------------------
console.log("== OBX skeleton seed generation ==");
console.log("output: " + OUT.pathname.replace(/^\//, ""));
let total = 0;
for (const [form, sk] of Object.entries(skeletons)) { total += sk.ids.length; console.log("  " + form.padEnd(6) + " " + String(sk.ids.length).padStart(3) + " OBX  (" + sk.file.replace(/_/g, " ") + ")"); }
console.log("total observations: " + total);
