/* Continuum Prompt 40: seed SQL generator. Reads the accreditation mapping
   workbook and emits clinical/db/002_seed_reference_and_lookups.sql, a faithful
   mirror of the reference data (spec Section 2 and 3): the code lists, the
   POB-NOI forbidden pairs, the contract/role/form matrix, plus the deterministic
   jurisdiction and fee schedule rows and the eight form_definition headers.

   Faithful mirror, not editor: every code cell is read as TEXT (01100 stays
   01100), every code is TRIMMED, extra columns are preserved in the extra jsonb.
   Composite lookup sheets whose first column is not a unique code (Category Type
   Expedite Codes, Form ID To Attachment Codes) are NOT flattened into a code
   list here; they are reported as deferred so nothing is silently mangled.

   NOT emitted here: form_element and form_rule. form_element needs a faithful
   per-form column parse gated on the verified element counts (a dedicated loader
   step), and form_rule loads from the human-reviewed transcription docs behind
   Hannah's clinical gate. Both are called out in clinical/db/README.md.

   Run: node clinical/db/seedgen.mjs "<path to mapping.xlsx>"
   No dashes anywhere. */

import * as XLSX from "xlsx";
import { readFileSync, writeFileSync } from "node:fs";

const path = process.argv[2];
if (!path) { console.error('usage: node seedgen.mjs "<mapping.xlsx>"'); process.exit(2); }
const OUT = new URL("./002_seed_reference_and_lookups.sql", import.meta.url);
const SRC = "2025.04";       // source_version stamped on every loaded row
const JUR = "AB";
const EFF = "2025-04-01";

const wb = XLSX.read(readFileSync(path), { type: "buffer" });
const sheet = (n) => wb.Sheets[n];
function ct(ws, r, c) { const a = XLSX.utils.encode_cell({ r, c }); const cell = ws[a]; if (!cell) return ""; return cell.w != null ? String(cell.w) : String(cell.v); }
function rangeOf(ws) { return XLSX.utils.decode_range(ws["!ref"]); }
const q = (v) => v === null || v === undefined ? "null" : "'" + String(v).replace(/'/g, "''") + "'";
const jb = (obj) => (obj && Object.keys(obj).length) ? "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb" : "null";

const out = [];
const audit = [];
out.push("-- Continuum Prompt 40: reference and lookup seed. GENERATED by clinical/db/seedgen.mjs.");
out.push("-- Faithful mirror of the accreditation workbook (source_version " + SRC + ").");
out.push("-- Apply AFTER 001_migration_wcb_engine.sql. One transaction. Idempotent (on conflict do nothing).");
out.push("-- Do not hand edit; regenerate from the workbook. No dashes anywhere.");
out.push("");
out.push("begin;");
out.push("");

// -- Section 1: jurisdiction (AB active, others inactive) --------------------
out.push("-- jurisdiction: Worker 36 active, every other province and territory inactive (spec Section 2).");
const JURS = [
  ["AB", "Worker 36", "batch_hl7", true], ["BC", "British Columbia", "none", false],
  ["MB", "Manitoba", "none", false], ["NB", "New Brunswick", "none", false],
  ["NL", "Newfoundland and Labrador", "none", false], ["NT", "Northwest Territories", "none", false],
  ["NS", "Nova Scotia", "none", false], ["NU", "Nunavut", "none", false],
  ["ON", "Ontario", "none", false], ["PE", "Prince Edward Island", "none", false],
  ["QC", "Quebec", "none", false], ["SK", "Saskatchewan", "none", false],
  ["YT", "Yukon", "none", false]
];
out.push("insert into clinical.jurisdiction(code,name,submission_channel,active) values");
out.push(JURS.map((j) => "  (" + q(j[0]) + "," + q(j[1]) + "," + q(j[2]) + "," + j[3] + ")").join(",\n") + "\non conflict (code) do nothing;");
out.push("");

// -- Section 2: fee schedule (Worker 36 GP rates, spec Section 2) --------------
out.push("-- wcb_fee_schedule: Worker 36 general practitioner rates effective 2025-04-01 (spec Section 2). Loaded as data, never hard coded elsewhere.");
const FEES = [
  ["C050E", "GP", "same_day", "96.98"], ["C050E", "GP", "on_time", "88.37"], ["C050E", "GP", "late", "55.70"],
  ["C151", "GP", "same_day", "58.91"], ["C151", "GP", "on_time", "53.69"], ["C151", "GP", "late", "33.85"]
];
out.push("insert into clinical.wcb_fee_schedule(jurisdiction_code,form_id,practitioner_role,fee_tier,amount,effective_from,source) values");
out.push(FEES.map((f) => "  (" + q(JUR) + "," + q(f[0]) + "," + q(f[1]) + "," + q(f[2]) + "," + f[3] + "," + q(EFF) + "," + q("Worker 36 WCB GP rates 2025-04-01 (spec Section 2)") + ")").join(",\n") + "\non conflict do nothing;");
out.push("");

// -- Section 3: code lists and values ---------------------------------------
const META = new Set(["Revision History", "Detailed Change Log", "Glossary", "Legend", "Section Mapping", "Batch File Elements and Values"]);
const FORMS = ["C050E", "C050S", "C151", "C151S", "C568", "C568A", "C569", "C570"];
const FORMSET = new Set(FORMS);
const SPECIAL = new Set(["POB-NOI Validations", "Contract ID Role Form ID Codes"]);

out.push("-- code lists (spec Section 2.1). One wcb_code_list per lookup worksheet, faithful mirror.");
let listCount = 0, valueCount = 0; const deferred = [];
for (const name of wb.SheetNames) {
  if (META.has(name) || FORMSET.has(name) || SPECIAL.has(name)) continue;
  const ws = sheet(name); const rg = rangeOf(ws);
  const header = []; for (let c = rg.s.c; c <= rg.e.c; c++) header.push(ct(ws, rg.s.r, c).trim());
  // code column: an exact "Code" header, else "Form ID", else the first column.
  let codeCol = header.findIndex((h) => /^code$/i.test(h));
  if (codeCol < 0) codeCol = header.findIndex((h) => /^form id$/i.test(h));
  if (codeCol < 0) codeCol = 0;
  let descCol = header.findIndex((h) => /description/i.test(h));
  if (descCol < 0) descCol = header.length > 1 ? 1 : 0;
  const rows = [];
  for (let r = rg.s.r + 1; r <= rg.e.r; r++) {
    const code = ct(ws, r, rg.s.c + codeCol).trim();
    if (code === "") continue;
    const description = ct(ws, r, rg.s.c + descCol).trim();
    const extra = {};
    for (let c = 0; c < header.length; c++) {
      if (c === codeCol || c === descCol || header[c] === "") continue;
      const v = ct(ws, r, rg.s.c + c).trim();
      if (v !== "") extra[header[c]] = v;
    }
    rows.push({ code, description, extra });
  }
  const codes = rows.map((x) => x.code);
  if (new Set(codes).size !== codes.length) { deferred.push(name + " (composite, first column is not a unique code)"); continue; }
  if (rows.some((x) => x.description.length > 200)) audit.push("WARN " + name + ": a description exceeds 200 chars and will be truncated by the column type");
  listCount++; valueCount += rows.length;
  out.push("insert into clinical.wcb_code_list(jurisdiction_code,list_name,source_version) values (" + q(JUR) + "," + q(name) + "," + q(SRC) + ") on conflict do nothing;");
  out.push("insert into clinical.wcb_code_value(list_id,list_name,code,description,sort_order,extra)");
  out.push("select l.id, v.list_name, v.code, v.description, v.sort_order, v.extra from clinical.wcb_code_list l");
  out.push("join (values");
  out.push(rows.map((x, i) => "  (" + q(name) + "," + q(x.code) + "," + q(x.description.slice(0, 200)) + "," + (i + 1) + "," + jb(x.extra) + ")").join(",\n"));
  out.push(") as v(list_name,code,description,sort_order,extra) on v.list_name=l.list_name");
  out.push("where l.list_name=" + q(name) + " and l.source_version=" + q(SRC) + " on conflict do nothing;");
  out.push("");
  audit.push("list " + name + ": " + rows.length + " values");
}

// -- Section 4: POB-NOI forbidden pairs --------------------------------------
out.push("-- wcb_pob_noi_forbidden: the POB-NOI combinations NOT allowed (spec Section 3, expect 380 Worker 36 rows).");
{
  const ws = sheet("POB-NOI Validations"); const rg = rangeOf(ws);
  // header at row s.r+1: NOI Code | NOI Description | POB Code | POB Description
  const pairs = [];
  for (let r = rg.s.r + 2; r <= rg.e.r; r++) {
    const noi = ct(ws, r, rg.s.c + 0).trim();
    const pob = ct(ws, r, rg.s.c + 2).trim();
    if (noi === "" && pob === "") continue;
    pairs.push([noi, pob]);
  }
  audit.push("POB-NOI forbidden rows: " + pairs.length + " (expect 380)");
  out.push("insert into clinical.wcb_pob_noi_forbidden(jurisdiction_code,noi_code,pob_code,source_version) values");
  out.push(pairs.map((p) => "  (" + q(JUR) + "," + q(p[0]) + "," + q(p[1]) + "," + q(SRC) + ")").join(",\n") + "\non conflict do nothing;");
  out.push("");
}

// -- Section 5: contract role and contract role form -------------------------
out.push("-- wcb_contract_role and wcb_contract_role_form (spec Section 2.2 and 3). Two tables in one sheet: Initial and Progress.");
{
  const ws = sheet("Contract ID Role Form ID Codes"); const rg = rangeOf(ws);
  const headerRows = [];
  for (let r = rg.s.r; r <= rg.e.r; r++) if (/^contract id$/i.test(ct(ws, r, rg.s.c).trim())) headerRows.push(r);
  const roleRows = new Map();   // "contract|role" -> {contract, cdesc, role, rdesc}
  const crf = [];               // {contract, role, form, kind, from}
  for (const hr of headerRows) {
    const header = []; for (let c = rg.s.c; c <= rg.e.c; c++) header.push(ct(ws, hr, c).trim());
    const kind = /progress/i.test(header[4] || "") ? "progress" : "initial";
    const fromCol = header.findIndex((h) => /can be created from/i.test(h));
    for (let r = hr + 1; r <= rg.e.r; r++) {
      const contract = ct(ws, r, rg.s.c + 0).trim();
      if (/^contract id$/i.test(contract)) break;
      const cdesc = ct(ws, r, rg.s.c + 1).trim();
      const role = ct(ws, r, rg.s.c + 2).trim();
      const rdesc = ct(ws, r, rg.s.c + 3).trim();
      const reports = ct(ws, r, rg.s.c + 4).trim();
      if (contract === "" && role === "" && reports === "") break;
      roleRows.set(contract + "|" + role, { contract, cdesc, role, rdesc });
      const froms = fromCol >= 0 ? ct(ws, r, rg.s.c + fromCol).split(",").map((s) => s.trim()).filter(Boolean) : [];
      for (const form of reports.split(",").map((s) => s.trim()).filter(Boolean))
        crf.push({ contract, role, form, kind, from: froms });
    }
  }
  audit.push("contract_role pairs: " + roleRows.size + " (expect 14); contract_role_form rows: " + crf.length + " (expect 66)");
  out.push("insert into clinical.wcb_contract_role(contract_id,contract_desc,practitioner_role,role_desc) values");
  out.push([...roleRows.values()].map((x) => "  (" + q(x.contract) + "," + q(x.cdesc) + "," + q(x.role) + "," + q(x.rdesc) + ")").join(",\n") + "\non conflict (contract_id,practitioner_role) do nothing;");
  out.push("");
  out.push("insert into clinical.wcb_contract_role_form(contract_id,practitioner_role,form_id,report_kind,created_from_form_ids,source_version) values");
  out.push(crf.map((x) => "  (" + q(x.contract) + "," + q(x.role) + "," + q(x.form) + "," + q(x.kind) + "," + (x.from.length ? "array[" + x.from.map(q).join(",") + "]::varchar(6)[]" : "null") + "," + q(SRC) + ")").join(",\n") + "\non conflict do nothing;");
  out.push("");
}

// -- Section 6: form_definition headers --------------------------------------
out.push("-- form_definition: the eight forms with their verified element counts (spec Section 4.1, acceptance criterion 4).");
{
  const EXPECTED = { C050E: 111, C050S: 171, C151: 136, C151S: 153, C568: 61, C568A: 69, C569: 37, C570: 66 };
  // max attachments per form from the Form ID Maximum Attachments sheet.
  const maxAtt = new Map();
  const mws = sheet("Form ID Maximum Attachments"); const mrg = rangeOf(mws);
  for (let r = mrg.s.r + 1; r <= mrg.e.r; r++) { const f = ct(mws, r, mrg.s.c).trim(); const n = ct(mws, r, mrg.s.c + 1).trim(); if (f) maxAtt.set(f, Number(n) || 0); }
  const defs = FORMS.map((f) => {
    const ws = sheet(f); const name = ct(ws, rangeOf(ws).s.r, rangeOf(ws).s.c).trim() || f;
    return { form: f, name, count: EXPECTED[f], max: maxAtt.get(f) || 0 };
  });
  out.push("insert into clinical.form_definition(jurisdiction_code,form_id,form_name,version,element_count,max_attachments,effective_from) values");
  out.push(defs.map((d) => "  (" + q(JUR) + "," + q(d.form) + "," + q(d.name.slice(0, 120)) + "," + q("1.0") + "," + d.count + "," + d.max + "," + q(EFF) + ")").join(",\n") + "\non conflict (jurisdiction_code,form_id,version) do nothing;");
  out.push("");
  defs.forEach((d) => audit.push("form_definition " + d.form + ": elements " + d.count + ", max_attachments " + d.max + ' ("' + d.name + '")'));
}

out.push("commit;");
out.push("");
writeFileSync(OUT, out.join("\n"), "utf8");

// -- audit report to stdout --------------------------------------------------
console.log("== Prompt 40 seed generation audit ==");
console.log("workbook: " + path);
console.log("output:   " + OUT.pathname.replace(/^\//, ""));
console.log("");
console.log("code lists emitted: " + listCount + " (" + valueCount + " values)");
audit.forEach((a) => console.log("  " + a));
console.log("");
console.log("DEFERRED composite sheets (not flattened, handled separately): " + (deferred.length ? "" : "none"));
deferred.forEach((d) => console.log("  " + d));
console.log("");
console.log("NOT emitted here (see clinical/db/README.md): form_element (per-form parse gated on counts), form_rule (transcription docs + Hannah clinical gate).");
